# Setup
title:               ntngps
tagline:             ''
description:         'Nadeem Persico-Shammas'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty
paginate_path:       '/page:num'

# About/contact
author:
  name:              Nadeem Persico-Shammas
  url:               https://instagram.com/ntngps
  email:             nadeem@ntngps.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Custom vars
# version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
